CREATE TABLE `post` (
  `id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `_deleted_fg` TINYINT(1) NOT NULL DEFAULT 0,
  `_created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `_updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
