---
services:
  dbh:
    dsn: 'dbi:mysql(RaiseError=>1,PrintError=>0):host=<%= $ENV{MYSQL_HOST} %>:port=<%= $ENV{MYSQL_PORT} %>:database=<%= $ENV{MYSQL_DATABASE} %>'
    user: '<%= $ENV{MYSQL_USER} %>'
    pass: '<%= $ENV{MYSQL_PASSWORD} %>'